name: lambdalab-ec-orden-ms-dev

services:
  postgres-ec-orden-ms-dev:
    image: postgres:16-alpine
    container_name: lambdalab-postgres-ec-orden-ms-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_ec_orden_ms
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom
    ports:
      - "49020:5432"
    volumes:
      - lambdalab_postgres_ec_orden_ms_dev_data:/var/lib/postgresql/data

volumes:
  lambdalab_postgres_ec_orden_ms_dev_data:
