name: lambdalab-pyspark

services:
  pyspark:
    container_name: lambdalab-pyspark
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/opt/notebooks
      - ./data:/opt/data
      - ./artifacts:/opt/artifacts
    environment:
      - JUPYTER_TOKEN=sintoken
