name: lambdalab-kafka-debezium

services:
  zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    container_name: lambdalab-kafka-debezium-zookeeper
    restart: unless-stopped
    ports:
      - "42181:2181"
    networks:
      - lambdalab-kafka-net

  kafka:
    image: debezium/kafka:2.7.3.Final
    container_name: lambdalab-kafka-debezium
    restart: unless-stopped
    ports:
      - "49092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      lambdalab-kafka-net:
        aliases:
          - kafka

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    container_name: lambdalab-kafka-debezium-exporter
    restart: unless-stopped
    command:
      - --kafka.server=kafka:9092
    depends_on:
      - kafka
    ports:
      - "49308:9308"
    networks:
      lambdalab-kafka-net:
        aliases:
          - kafka-exporter

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: lambdalab-kafka-debezium-ui
    restart: unless-stopped
    ports:
      - "48085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: lambdalab-kafka-debezium
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - lambdalab-kafka-net

  connect:
    image: debezium/connect:2.7.3.Final
    container_name: lambdalab-kafka-debezium-connect
    restart: unless-stopped
    ports:
      - "48083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
      STATUS_STORAGE_TOPIC: "connect_statuses"
    depends_on:
      - kafka
    networks:
      - lambdalab-kafka-net

networks:
  lambdalab-kafka-net:
    name: lambdalab-kafka-net
